services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - smarthome-network
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./monitoring/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5  
    ports:
      - "5432:5432"

  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api-app
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081

    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  monitoring-app:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    container_name: monitoring-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/monitoring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - PORT=8082
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - smarthome-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge